#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAIN_QML="${ROOT_DIR}/contents/ui/main.qml"
GENERAL_QML="${ROOT_DIR}/contents/ui/configGeneral.qml"
DISPLAY_QML="${ROOT_DIR}/contents/ui/configDisplay.qml"
ADVANCED_QML="${ROOT_DIR}/contents/ui/configAdvanced.qml"
ABOUT_QML="${ROOT_DIR}/contents/ui/configAbout.qml"
DEBUG_QML="${ROOT_DIR}/contents/ui/configDebug.qml"
PROVIDERS_QML="${ROOT_DIR}/contents/ui/configProviders.qml"
README_MD="${ROOT_DIR}/README.md"
TODO_MD="${ROOT_DIR}/TODO.md"
CONFIG_XML="${ROOT_DIR}/contents/config/main.xml"
CONFIG_QML="${ROOT_DIR}/contents/config/config.qml"
MAKEFILE="${ROOT_DIR}/Makefile"

require_in_file() {
  local file="$1"
  local needle="$2"
  if ! grep -Fq -- "$needle" "$file"; then
    echo "missing expected fragment in ${file#"$ROOT_DIR"/}: $needle" >&2
    exit 1
  fi
}

reject_in_file() {
  local file="$1"
  local needle="$2"
  if grep -Fq -- "$needle" "$file"; then
    echo "unexpected fragment in ${file#"$ROOT_DIR"/}: $needle" >&2
    exit 1
  fi
}

require_in_file "$PROVIDERS_QML" "property string selectedProviderID"
require_in_file "$PROVIDERS_QML" "function setApiKey(providerID)"
require_in_file "$PROVIDERS_QML" "function loadProviderSettings(providerID)"
require_in_file "$PROVIDERS_QML" "function handleDiagnoseResult(descriptor, stdoutText, stderrText)"
require_in_file "$PROVIDERS_QML" "function providerSettingsRows(item)"
require_in_file "$PROVIDERS_QML" "function providerCliCommandText(item)"
require_in_file "$PROVIDERS_QML" "property var providerDiagnostics"
require_in_file "$PROVIDERS_QML" "kdialog --password"
require_in_file "$PROVIDERS_QML" "config set-api-key --provider"
require_in_file "$PROVIDERS_QML" "diagnose --provider"
require_in_file "$PROVIDERS_QML" "--format json --redact"
require_in_file "$PROVIDERS_QML" "--stdin --format json --json-only"
require_in_file "$PROVIDERS_QML" "function providerDocsUrl(providerID)"
require_in_file "$PROVIDERS_QML" "function providerLoginUrl(providerID)"
require_in_file "$PROVIDERS_QML" "function supportsApiKeySetup(providerID)"
require_in_file "$PROVIDERS_QML" "action: \"set-api-key\""
require_in_file "$PROVIDERS_QML" "Provider settings"
require_in_file "$PROVIDERS_QML" "Load redacted settings"
require_in_file "$PROVIDERS_QML" "CLI commands"

require_in_file "$MAIN_QML" "daily: normalizeCostDaily(item.daily, currency)"
require_in_file "$MAIN_QML" "totals: normalizeCostTotals(item.totals, item.last30DaysCostUSD, item.last30DaysTokens, currency)"
require_in_file "$MAIN_QML" "models: normalizeCostModels(item.daily, currency)"
require_in_file "$MAIN_QML" "function normalizeCostDaily(items, currency)"
require_in_file "$MAIN_QML" "function normalizeCostTotals(totals, fallbackCost, fallbackTokens, currency)"
require_in_file "$MAIN_QML" "function normalizeCostModels(items, currency)"
require_in_file "$MAIN_QML" "function costBreakdownRows(tokenCost)"
require_in_file "$MAIN_QML" "function costModelRows(tokenCost)"
require_in_file "$MAIN_QML" "function costDailyRows(tokenCost)"
require_in_file "$MAIN_QML" "function costHistoryRows(tokenCost)"
require_in_file "$MAIN_QML" "function costPeakLine(points)"
require_in_file "$MAIN_QML" "function costAverageDailyLine(points)"
require_in_file "$MAIN_QML" "function costPerMillionLine(tokenCost)"
require_in_file "$MAIN_QML" "function compactCostTokenSummary(cost, tokens, currency)"
require_in_file "$MAIN_QML" "Canvas {"
require_in_file "$MAIN_QML" "id: costSparkline"
require_in_file "$MAIN_QML" "id: costHistoryChartSection"
require_in_file "$MAIN_QML" "id: costDrillDownSection"
require_in_file "$MAIN_QML" "model: costDrillDownSection.breakdownRows"
require_in_file "$MAIN_QML" "model: costDrillDownSection.modelRows"
require_in_file "$MAIN_QML" "model: costDrillDownSection.dailyRows"
require_in_file "$MAIN_QML" "model: costHistoryChartSection.rows"
require_in_file "$MAIN_QML" "function providerDocsUrl(providerID)"
require_in_file "$MAIN_QML" "function providerLoginUrl(providerID)"
require_in_file "$MAIN_QML" "action: \"docs\""
require_in_file "$MAIN_QML" "function buildProviderAccountsCommand(providerID)"
require_in_file "$MAIN_QML" "--all-accounts"
require_in_file "$MAIN_QML" "function selectedAccountForProvider(providerID)"
require_in_file "$MAIN_QML" "--account"
require_in_file "$MAIN_QML" "function selectAccount(providerID, accountLabel)"
require_in_file "$MAIN_QML" "function accountOptionsForProvider(providerID)"
require_in_file "$MAIN_QML" "action: \"accounts\""
require_in_file "$MAIN_QML" "property string menuBarDisplayMode"
require_in_file "$MAIN_QML" "property bool resetTimesShowAbsolute"
require_in_file "$MAIN_QML" "function menuBarDisplayText(item)"
require_in_file "$MAIN_QML" "function primaryPaceText(item)"
require_in_file "$MAIN_QML" "function primaryResetText(item)"
require_in_file "$MAIN_QML" "function resetText(window, absolute)"
require_in_file "$MAIN_QML" "Plasmoid.configuration.menuBarDisplayMode"
require_in_file "$MAIN_QML" "onResetTimesShowAbsoluteChanged: Qt.callLater(refreshNow)"
require_in_file "$MAIN_QML" "property bool showQuotaWarningMarkers"
require_in_file "$MAIN_QML" "function statusSeverity(status)"
require_in_file "$MAIN_QML" "function statusBadgeColor(severity)"
require_in_file "$MAIN_QML" "function primaryIncidentProvider()"
require_in_file "$MAIN_QML" "id: compactStatusBadge"
require_in_file "$MAIN_QML" "id: providerStatusBadge"
require_in_file "$MAIN_QML" "function quotaWarningMarkers(row)"
require_in_file "$MAIN_QML" "quotaWarningMarkerRepeater"
require_in_file "$MAIN_QML" "showQuotaWarningMarkers"
require_in_file "$MAIN_QML" "property bool enableNotifications"
require_in_file "$MAIN_QML" "property bool autoSelectProvider"
require_in_file "$MAIN_QML" "Math.max(0, Number(Plasmoid.configuration.refreshInterval))"
require_in_file "$MAIN_QML" "function updateSelectedProvider()"
require_in_file "$MAIN_QML" "function autoSelectedProviderIndex()"
require_in_file "$MAIN_QML" "function autoSelectScore(item)"
require_in_file "$MAIN_QML" "function autoSelectUsedPercent(item)"
require_in_file "$MAIN_QML" "function selectedCompactProvider()"
require_in_file "$MAIN_QML" "interval: root.refreshIntervalSec > 0 ? root.refreshIntervalSec * 1000 : 0"
require_in_file "$MAIN_QML" "property var notificationMemo"
require_in_file "$MAIN_QML" "function processNotifications()"
require_in_file "$MAIN_QML" "function primeNotifications()"
require_in_file "$MAIN_QML" "function quotaNotificationLevel(row)"
require_in_file "$MAIN_QML" "function notificationUrgency(severity)"
require_in_file "$MAIN_QML" "function sendPlasmaNotification(title, body, urgency)"
require_in_file "$MAIN_QML" "function processLimitResetNotifications(item, nextMemo)"
require_in_file "$MAIN_QML" "notify-send --app-name=CodexBar"
require_in_file "$MAIN_QML" "notificationSource.connectSource(command)"

require_in_file "$GENERAL_QML" "Fetch provider status"
require_in_file "$GENERAL_QML" "Enable Plasma notifications"
require_in_file "$GENERAL_QML" "Notify status incidents"
require_in_file "$GENERAL_QML" "Notify quota warnings"
require_in_file "$GENERAL_QML" "Notify limit resets"
require_in_file "$GENERAL_QML" "Refresh preset:"
require_in_file "$GENERAL_QML" "function refreshPresetIndex(value)"
require_in_file "$GENERAL_QML" "onCfg_refreshIntervalChanged"
require_in_file "$GENERAL_QML" "Manual"
require_in_file "$GENERAL_QML" "1 min"
require_in_file "$GENERAL_QML" "2 min"
require_in_file "$GENERAL_QML" "5 min"
require_in_file "$GENERAL_QML" "15 min"
require_in_file "$GENERAL_QML" "Custom"

require_in_file "$CONFIG_QML" "configDisplay.qml"
require_in_file "$CONFIG_QML" "configAdvanced.qml"
require_in_file "$CONFIG_QML" "configAbout.qml"
require_in_file "$CONFIG_QML" "configDebug.qml"

require_in_file "$MAKEFILE" "scripts/test_qml_hardening.sh"
require_in_file "$MAKEFILE" "QMLLINT_FLAGS ?= --unqualified disable"

require_in_file "$DISPLAY_QML" "Display mode:"
require_in_file "$DISPLAY_QML" "Show usage as percent used"
require_in_file "$DISPLAY_QML" "Show quota warning markers"
require_in_file "$DISPLAY_QML" "Show reset times as clock time"
require_in_file "$DISPLAY_QML" "Show multi-provider details in panel"
require_in_file "$DISPLAY_QML" "Auto-select highest-usage provider"

require_in_file "$ADVANCED_QML" "Advanced provider override"
require_in_file "$ADVANCED_QML" "Provider id (blank = all enabled)"
require_in_file "$ADVANCED_QML" "Provider default (blank)"

require_in_file "$ABOUT_QML" "CodexBar Plasma"
require_in_file "$ABOUT_QML" "Upstream CodexBar"
require_in_file "$ABOUT_QML" "Qt.openUrlExternally"

require_in_file "$DEBUG_QML" "function runDiagnostic()"
require_in_file "$DEBUG_QML" "diagnose --provider"
require_in_file "$DEBUG_QML" "--format json --redact"
require_in_file "$DEBUG_QML" "id: diagnosticOutputArea"

require_in_file "$CONFIG_XML" "autoSelectProvider"
require_in_file "$CONFIG_XML" "notifyLimitResets"

require_in_file "$README_MD" "Display mode"
require_in_file "$README_MD" "incident badge"
require_in_file "$README_MD" "quota warning markers"
require_in_file "$README_MD" "Plasma notifications"
require_in_file "$README_MD" "a heavily used limit resets back to empty"
require_in_file "$README_MD" "cost drill-down"
require_in_file "$README_MD" "Refresh presets"
require_in_file "$README_MD" "Auto-select highest-usage provider"
require_in_file "$README_MD" "latest release"
require_in_file "$README_MD" "codexbar-plasma.plasmoid"
require_in_file "$README_MD" "## Troubleshooting"
require_in_file "$README_MD" "## Development"

reject_in_file "$TODO_MD" "Release automation:"
require_in_file "$TODO_MD" "Provider-specific editable settings"
require_in_file "$TODO_MD" "Interactive history charts"
require_in_file "$TODO_MD" "Dashboard extras"
require_in_file "$TODO_MD" "Translations"

require_in_file "$README_MD" "yay -S codexbar-cli"
require_in_file "$README_MD" "kpackagetool6 -t Plasma/Applet -i codexbar-plasma.plasmoid"
require_in_file "$README_MD" "kpackagetool6 -t Plasma/Applet -u codexbar-plasma.plasmoid"
require_in_file "$README_MD" "kpackagetool6 -t Plasma/Applet -u ."
require_in_file "$README_MD" "systemctl --user restart plasma-plasmashell.service"
require_in_file "$README_MD" "codexbar usage --provider codex --all-accounts --format json --json-only"

reject_in_file "$MAIN_QML" "console.log(\"CodexBar"
reject_in_file "$PROVIDERS_QML" "console.log(\"CodexBar"

echo "KDE plasmoid feature parity checks passed."
